# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Stephanie Sobrepera, MD"
description: > # this means to ignore newlines until "email:"
   A blog about life as a young physician

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/StephMDLogo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/juja-han-unsplash.jpg"

name: 'Stephanie Sobrepera'
author: 'Stephanie Sobrepera'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@stephsobrepera'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/stephsobrepera
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/stephaniekimberlynguyen
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	instagram
    url:	https://www.instagram.com/lafleurfascinant/
    desc:	Follow me on insta
    share_url:
    share_title:
    share_link:

  - icon:	medium-m
    url:	https://www.medium.com/@stephaniesobrepera
    desc:	Read my stories on Medium
    share_url:
    share_title:
    share_link:

  # - icon:	github
    # url:	https://github.com/stephanieknguyen
    # desc:	Fork me on github
    # share_url:
    # share_title:
    # share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
